name: RP

on:
  push:
    branches:
      - main
    paths:
      - 'OA/s/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    if: "github.event_name == 'push' && github.ref == 'refs/heads/main' && !startsWith(github.event.head_commit.message, 'chore: release OA')"
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: 🚀 Release please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          path: OA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 🗃 Do checkout
        uses: actions/checkout@v4
