name: Release Please Release

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
    outputs:
      released:
        value: ${{ jobs.release.outputs.released }}
      tag_name:
        value: ${{ jobs.release.outputs.tag_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release.outputs[format('{0}--release_created', inputs.path)] }}
      tag_name: ${{ steps.release.outputs[format('{0}--release_created', inputs.path)] && format('{0}.{1}.{2}', steps.release.outputs[format('{0}--major', inputs.path)], steps.release.outputs[format('{0}--minor', inputs.path)], steps.release.outputs[format('{0}--patch', inputs.path)]) || '' }}
    steps:
      - name: 🚀 Release please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          path: ${{ inputs.path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
